#!/usr/bin/env node
// Kernel config generator: a local, dependency-free web app for building
// kernel.ini visually -- add module nodes, drag-connect dependency pins,
// edit per-module config, and write the result back to the repo's root
// kernel.ini. See modules/*/module.ini for the schema this reads and
// bootloader/modules/module_loader.zig for the kernel.ini grammar this
// mirrors.
"use strict";

const http = require("http");
const fs = require("fs");
const path = require("path");
const url = require("url");

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const MODULES_DIR = path.join(REPO_ROOT, "modules");
const KERNEL_INI_PATH = path.join(REPO_ROOT, "kernel.ini");
const LAYOUT_PATH = path.join(__dirname, "layout.json");
const PUBLIC_DIR = path.join(__dirname, "public");
const PORT = process.env.PORT ? Number(process.env.PORT) : 5175;

const DEFAULT_HEADER = [
  "; One [module_name] section per module, each with its own enable flag",
  "; and (if it imports anything) a sibling [module_name.dependencies]",
  "; section wiring each interface type it needs to the module that provides",
  "; it, plus a sibling [module_name.config] section setting any config",
  "; values the module declared (see its module.ini). Generated by the",
  "; configurator app (tools/configurator) -- hand edits above the first",
  "; section header are preserved across regeneration; edits below it are not.",
  "",
].join("\n");

// --- Generic INI parsing --------------------------------------------
//
// Mirrors module_loader.zig's parseConfig line semantics exactly: strip
// ';'/'#' comments, trim whitespace, '[name]' starts a section, 'key =
// value' takes the first '=' as the split point and only the *second*
// '='-delimited token as the value (matching Zig's splitScalar().next()
// twice -- a third '=' in a line silently truncates the value there too).
function parseIniSections(text) {
  const sections = [];
  let current = null;
  for (const rawLine of text.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith(";") || line.startsWith("#")) continue;
    if (line.startsWith("[") && line.endsWith("]")) {
      current = { name: line.slice(1, -1).trim(), entries: [] };
      sections.push(current);
      continue;
    }
    if (!current) continue;
    const parts = line.split("=");
    if (parts.length < 2) continue;
    const key = parts[0].trim();
    const value = parts[1].trim();
    current.entries.push([key, value]);
  }
  return sections;
}

// --- module.ini -------------------------------------------------------

function parseModuleIni(text) {
  const sections = parseIniSections(text);
  const byName = new Map(sections.map((s) => [s.name, s]));

  const moduleSec = byName.get("module");
  const nameEntry = moduleSec && moduleSec.entries.find(([k]) => k === "name");
  const name = nameEntry ? nameEntry[1] : null;

  const provides = [];
  const providesSec = byName.get("provides");
  if (providesSec) for (const [instance, type] of providesSec.entries) provides.push({ instance, type });

  const requires = [];
  const requiresSec = byName.get("requires");
  if (requiresSec) for (const [key, type] of requiresSec.entries) requires.push({ key, type });

  const config = [];
  const configSec = byName.get("config");
  if (configSec) {
    const keysEntry = configSec.entries.find(([k]) => k === "keys");
    const keys = keysEntry
      ? keysEntry[1].split(",").map((s) => s.trim()).filter(Boolean)
      : [];
    for (const key of keys) {
      const fieldSec = byName.get(`config.${key}`);
      const field = { key, type: "str", default: "" };
      if (fieldSec) for (const [k, v] of fieldSec.entries) field[k] = v;
      config.push(field);
    }
  }

  return { name, provides, requires, config };
}

function walkModules(rootDir) {
  const results = [];
  function walk(dir, relParts) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), [...relParts, entry.name]);
      } else if (entry.isFile() && entry.name === "module.ini") {
        const dotted = relParts.join(".");
        const text = fs.readFileSync(path.join(dir, entry.name), "utf8");
        const parsed = parseModuleIni(text);
        results.push({
          name: parsed.name || dotted,
          dir: relParts.join("/"),
          provides: parsed.provides,
          requires: parsed.requires,
          config: parsed.config,
        });
      }
    }
  }
  walk(rootDir, []);
  results.sort((a, b) => a.name.localeCompare(b.name));
  return results;
}

// --- kernel.ini ---------------------------------------------------------

const DEPENDENCIES_SUFFIX = ".dependencies";
const CONFIG_SUFFIX = ".config";

function parseKernelIni(text) {
  const sections = parseIniSections(text);
  const modules = new Map();
  const order = [];
  const edges = [];

  function ensure(name) {
    let mod = modules.get(name);
    if (!mod) {
      mod = { name, enabled: false, config: {} };
      modules.set(name, mod);
      order.push(name);
    }
    return mod;
  }

  for (const sec of sections) {
    if (sec.name.endsWith(DEPENDENCIES_SUFFIX)) {
      const owner = sec.name.slice(0, -DEPENDENCIES_SUFFIX.length);
      ensure(owner);
      for (const [type, provider] of sec.entries) edges.push({ consumer: owner, type, provider });
    } else if (sec.name.endsWith(CONFIG_SUFFIX)) {
      const owner = sec.name.slice(0, -CONFIG_SUFFIX.length);
      const mod = ensure(owner);
      for (const [key, value] of sec.entries) mod.config[key] = value;
    } else {
      const mod = ensure(sec.name);
      for (const [key, value] of sec.entries) {
        if (key !== "enable") continue;
        mod.enabled = value.length > 0 && (value[0] === "t" || value[0] === "T" || value[0] === "1");
      }
    }
  }

  return { modules: order.map((n) => modules.get(n)), edges };
}

function extractHeader(text) {
  const lines = text.split("\n");
  const header = [];
  for (const line of lines) {
    if (line.trim().startsWith("[")) break;
    header.push(line);
  }
  while (header.length && header[header.length - 1].trim() === "") header.pop();
  return header.length ? header.join("\n") + "\n\n" : "";
}

function generateKernelIni(graph, existingText) {
  const header = extractHeader(existingText || "") || DEFAULT_HEADER + "\n";
  const out = [header.replace(/\s+$/, "")];

  for (const mod of graph.modules || []) {
    const block = [`[${mod.name}]`, `enable = ${mod.enabled ? "true" : "false"}`];

    const deps = (graph.edges || []).filter((e) => e.consumer === mod.name);
    if (deps.length) {
      block.push(`[${mod.name}.dependencies]`);
      for (const d of deps) block.push(`${d.type} = ${d.provider}`);
    }

    const configEntries = Object.entries(mod.config || {}).filter(([, v]) => v !== null && v !== undefined && v !== "");
    if (configEntries.length) {
      block.push(`[${mod.name}.config]`);
      for (const [k, v] of configEntries) block.push(`${k} = ${v}`);
    }

    out.push(block.join("\n"));
  }

  return out.join("\n\n") + "\n";
}

// --- HTTP plumbing --------------------------------------------------

function sendJson(res, status, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": Buffer.byteLength(body),
  });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
};

function serveStatic(res, pathname) {
  const rel = pathname === "/" ? "/index.html" : pathname;
  const filePath = path.normalize(path.join(PUBLIC_DIR, rel));
  if (!filePath.startsWith(PUBLIC_DIR)) {
    res.writeHead(403);
    res.end();
    return;
  }
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404);
      res.end("Not found");
      return;
    }
    res.writeHead(200, {
      "Content-Type": MIME[path.extname(filePath)] || "application/octet-stream",
      // This is actively-edited local dev tooling -- never let the browser
      // cache a stale copy of app.js/style.css across a reload.
      "Cache-Control": "no-store",
    });
    res.end(data);
  });
}

const server = http.createServer(async (req, res) => {
  const parsed = url.parse(req.url, true);
  try {
    if (parsed.pathname === "/api/modules" && req.method === "GET") {
      sendJson(res, 200, walkModules(MODULES_DIR));
      return;
    }

    if (parsed.pathname === "/api/kernel-ini" && req.method === "GET") {
      const text = fs.existsSync(KERNEL_INI_PATH) ? fs.readFileSync(KERNEL_INI_PATH, "utf8") : "";
      sendJson(res, 200, parseKernelIni(text));
      return;
    }

    if (parsed.pathname === "/api/kernel-ini" && req.method === "POST") {
      const graph = JSON.parse(await readBody(req));
      const existing = fs.existsSync(KERNEL_INI_PATH) ? fs.readFileSync(KERNEL_INI_PATH, "utf8") : "";
      const text = generateKernelIni(graph, existing);
      fs.writeFileSync(KERNEL_INI_PATH, text);
      sendJson(res, 200, { ok: true, path: path.relative(REPO_ROOT, KERNEL_INI_PATH) });
      return;
    }

    if (parsed.pathname === "/api/layout" && req.method === "GET") {
      const layout = fs.existsSync(LAYOUT_PATH) ? JSON.parse(fs.readFileSync(LAYOUT_PATH, "utf8")) : {};
      sendJson(res, 200, layout);
      return;
    }

    if (parsed.pathname === "/api/layout" && req.method === "POST") {
      const body = await readBody(req);
      JSON.parse(body); // validate
      fs.writeFileSync(LAYOUT_PATH, body);
      sendJson(res, 200, { ok: true });
      return;
    }

    if (req.method === "GET") {
      serveStatic(res, parsed.pathname);
      return;
    }

    res.writeHead(404);
    res.end();
  } catch (err) {
    sendJson(res, 500, { error: String((err && err.stack) || err) });
  }
});

server.listen(PORT, () => {
  console.log(`Kernel configurator running at http://localhost:${PORT}`);
  console.log(`Repo root: ${REPO_ROOT}`);
});
